# Generated by Django 2.2.2 on 2020-06-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AUDIENCIA',
            fields=[
                ('AUDIENCIA_id', models.AutoField(primary_key=True, serialize=False)),
                ('RESUMEN', models.TextField()),
            ],
        ),
    ]
